export const products = [
  // Fruits
  {
    id: 1,
    name: "Yellow Mango",
    price: 120,
    image: "/images/yellow-mango.png",
    category: "Fruits",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 2,
    name: "Langra Mango",
    price: 40,
    image: "/images/langra-mango.png",
    category: "Fruits",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 3,
    name: "Raw Mango",
    price: 60,
    image: "/images/raw-mango.png",
    category: "Fruits",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 4,
    name: "Aloo Bafara",
    price: 160,
    image: "/images/alphonso-mango.png",
    category: "Fruits",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Premium",
  },
  {
    id: 5,
    name: "Papaya",
    price: 60,
    image: "/images/papaya.png",
    category: "Fruits",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 6,
    name: "Banana",
    price: 50,
    image: "/images/banana.png",
    category: "Fruits",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Popular",
  },

  // Vegetables
  {
    id: 7,
    name: "Khira",
    price: 50,
    image: "/images/cucumber.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 8,
    name: "Lauki",
    price: 40,
    image: "/images/bottle-gourd.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 9,
    name: "Karela",
    price: 40,
    image: "/images/bitter-gourd.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 10,
    name: "Arbi",
    price: 50,
    image: "/images/taro-root.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 11,
    name: "Aariya",
    price: 30,
    image: "/images/fig-leaf-gourd.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 12,
    name: "Shimla Mirch",
    price: 80,
    image: "/images/capsicum.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 13,
    name: "Matri",
    price: 30,
    image: "/images/cluster-beans.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 14,
    name: "Petha",
    price: 20,
    image: "/images/ash-gourd.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 15,
    name: "Bhindi",
    price: 40,
    image: "/images/okra.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 16,
    name: "Chaulai Ki Fali",
    price: 100,
    image: "/images/amaranth-pods.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Premium",
  },
  {
    id: 17,
    name: "Badi Fali",
    price: 60,
    image: "/images/broad-beans.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 18,
    name: "Choti Fali",
    price: 80,
    image: "/images/french-beans.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 19,
    name: "Tindsi",
    price: 40,
    image: "/images/apple-gourd.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 20,
    name: "Baingan",
    price: 40,
    image: "/images/brinjal.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 21,
    name: "Kachar",
    price: 30,
    image: "/images/kachri.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
];