export const products = [
  {
    id: 1,
    name: "Apple",
    price: 120,
    image: "/images/apple.png",
    category: "Fruits",
    discount: "20% OFF",
    rating: "⭐⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Best Seller",
  },
  {
    id: 2,
    name: "Banana",
    price: 60,
    image: "/images/banana.png",
    category: "Fruits",
    discount: "15% OFF",
    rating: "⭐⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 3,
    name: "Orange",
    price: 80,
    image: "/images/orange.png",
    category: "Fruits",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Popular",
  },
  {
    id: 4,
    name: "Mango",
    price: 150,
    image: "/images/mango.png",
    category: "Fruits",
    discount: "25% OFF",
    rating: "⭐⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Best Seller",
  },
  {
    id: 5,
    name: "Grapes",
    price: 90,
    image: "/images/grapes.png",
    category: "Fruits",
    discount: "18% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 6,
    name: "Watermelon",
    price: 50,
    image: "/images/watermelon.png",
    category: "Fruits",
    discount: "12% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Hot",
  },
  {
    id: 7,
    name: "Tomato",
    price: 40,
    image: "/images/tomato.png",
    category: "Vegetables",
    discount: "15% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
  {
    id: 8,
    name: "Potato",
    price: 30,
    image: "/images/potato.png",
    category: "Vegetables",
    discount: "10% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Popular",
  },
  {
    id: 9,
    name: "Onion",
    price: 35,
    image: "/images/onion.png",
    category: "Vegetables",
    discount: "20% OFF",
    rating: "⭐⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Best Seller",
  },
  {
    id: 10,
    name: "Carrot",
    price: 45,
    image: "/images/carrot.png",
    category: "Vegetables",
    discount: "8% OFF",
    rating: "⭐⭐⭐⭐",
    stock: "In Stock",
    badge: "Fresh",
  },
];